#!/usr/bin/env python3
# -*- coding: utf-8 -*-

'''
################################################################################
#                                                                              #
# eudaimon                                                                     #
#                                                                              #
################################################################################
#                                                                              #
# LICENCE INFORMATION                                                          #
#                                                                              #
# This program is an interface to OpenAI models via the OpenAI API.            #
#                                                                              #
# copyright (C) 2024 William Breaden Madden                                    #
#                                                                              #
# This software is released under the terms of the GNU General Public License  #
# version 3 (GPLv3).                                                           #
#                                                                              #
# This program is free software: you can redistribute it and/or modify it      #
# under the terms of the GNU General Public License as published by the Free   #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This program is distributed in the hope that it will be useful, but WITHOUT  #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for     #
# more details.                                                                #
#                                                                              #
# For a copy of the GNU General Public License, see                            #
# <http://www.gnu.org/licenses>.                                               #
#                                                                              #
################################################################################
'''

import os
import sys

from openai import OpenAI

__version__ = '2024-06-10T1804Z'

def main():
    api_key = os.getenv('OPENAI_API_KEY')
    if not api_key:
        print('OPENAI_API_KEY environment variable not set')
        sys.exit(1)
    text_input = ' '.join(sys.argv[1:])
    if not text_input:
        print('no input provided')
        sys.exit(1)
    try:
        client = OpenAI()
    except Exception as e:
        print(f'error: {str(e)}')
        sys.exit(1)
    try:
        completion = client.chat.completions.create(
            model='gpt-4o',
            messages=[{'role': 'user', 'content': text_input}]
        )
    except Exception as e:
        print(f'error: {str(e)}')
        sys.exit(1)
    print(completion.choices[0].message.content)

if __name__ == '__main__':
    main()
